name: CI/CD Cube JS EC2

on:
  push:
    branches: [ master ]
    paths: ['CubeJS/schema/**'] #validate this


jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd home/${USER_NAME}/cube-quext-dev &&
            git sparse-checkout set CubeJS &&
            #Please validate all the git commands to only copy the content inside the CubeJS/schema folder
            #git pull origin master
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master #&&
            #Docker commands to run everytime is a new thing added
          '
