name: CI/CD Cube JS EC2

on:
  push:
    branches: [ master ]
    paths: ['CubeJS/schema/**'] #validate this
    

jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          rsync -avz --delete ./CubeJS/schema ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }}:/home/${{ secrets.USER_NAME }}/cube-dev-quext 
          ssh -i private_key.pem ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }}
          '
          cd /home/${{ secrets.USER_NAME }}/cube-dev-quext
            #Now we have got the access of EC2 and we will start the deploy .
            sudo mkdir -p /home/${{ secrets.USER_NAME }}/cube-dev-quext/CubeJS/schema &&
            cd /home/${{ secrets.USER_NAME }}/cube-dev-quext/CubeJS/schema
            #Docker commands to run everytime is a new thing added
            #docker-compose up && docker-compose down -d
          '
